# Unsupervised Learning Techniques

In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

In [3]:
X, y = make_blobs(random_state=1)

In [22]:
k = 5
kmean = KMeans(n_clusters=k)
y_pred = kmean.fit_predict(X)

In [23]:
y_pred

array([1, 4, 0, 0, 2, 2, 2, 4, 3, 1, 4, 0, 2, 3, 2, 2, 2, 1, 0, 0, 2, 0,
       2, 1, 4, 2, 2, 1, 1, 2, 3, 1, 2, 1, 4, 2, 4, 0, 4, 2, 2, 4, 1, 0,
       4, 2, 3, 1, 3, 1, 4, 2, 2, 2, 3, 2, 0, 0, 3, 1, 0, 2, 2, 4, 0, 2,
       3, 2, 1, 4, 0, 4, 2, 3, 3, 4, 2, 2, 1, 0, 3, 0, 0, 2, 1, 1, 3, 1,
       0, 3, 2, 1, 3, 0, 4, 2, 2, 3, 2, 1], dtype=int32)

In [24]:
kmean.labels_

array([1, 4, 0, 0, 2, 2, 2, 4, 3, 1, 4, 0, 2, 3, 2, 2, 2, 1, 0, 0, 2, 0,
       2, 1, 4, 2, 2, 1, 1, 2, 3, 1, 2, 1, 4, 2, 4, 0, 4, 2, 2, 4, 1, 0,
       4, 2, 3, 1, 3, 1, 4, 2, 2, 2, 3, 2, 0, 0, 3, 1, 0, 2, 2, 4, 0, 2,
       3, 2, 1, 4, 0, 4, 2, 3, 3, 4, 2, 2, 1, 0, 3, 0, 0, 2, 1, 1, 3, 1,
       0, 3, 2, 1, 3, 0, 4, 2, 2, 3, 2, 1], dtype=int32)

In [25]:
y_pred is kmean.labels_

True

In [26]:
kmean.cluster_centers_

array([[-10.468699  ,  -3.31041475],
       [ -1.33824945,   3.58202335],
       [ -6.58196786,  -8.17239339],
       [ -1.63933544,   5.29379975],
       [ -9.54613654,  -4.51849239]])

In [27]:
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])
kmean.predict(X_new)

array([1, 1, 1, 1], dtype=int32)

In [28]:
X_new

array([[ 0. ,  2. ],
       [ 3. ,  2. ],
       [-3. ,  3. ],
       [-3. ,  2.5]])

In [40]:
kmean.transform(X_new)

array([[11.73857587,  2.0721268 , 12.11610037,  3.67920338, 11.55938865],
       [14.47778842,  4.61770573, 13.97468051,  5.68968805, 14.13846827],
       [ 9.77766838,  1.76072885, 11.7325559 ,  2.66700681,  9.96893331],
       [ 9.46268378,  1.98297489, 11.25746306,  3.10752717,  9.59745482]])